##===- lib/CStdLib/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../../../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=cstdlib
BUILD_ARCHIVE := 1
ifneq ($(OS),Cygwin)
ifneq ($(OS),MingW)
SHARED_LIBRARY := 1
LOADABLE_MODULE := 1
endif
endif

#
# Include projects/safecode/Makefile.common so we know what to do.
#
include $(LEVEL)/projects/safecode/Makefile.common

